footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]
footprint_padding: 0.1

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

#layer definitions

static_layer:
  enabled:              true
  map_topic:            map

obstacle_layer:
  observation_sources: laser_scan_sensor point_clout_sensor
  laser_scan_sensor:
    topic: scan_filtered
    observation_persistence: 0.0 # How long to keep each sensor reading in seconds. A value of 0.0 will only keep the most recent reading.
    #   expected_update_rate: 0 # if zero, the observation buffer returns isCurrent=true always
    data_type: LaserScan
    obstacle_range: 5.0 # 5.0
    raytrace_range: 6.5 #5.0
    inf_is_valid: true
    min_obstacle_height: -0.5
    marking: true
    clearing: true
    track_unknown_space: true # true needed for disabling global path planning through unknown space
    footprint_clearing_enabled: true
    combination_method: 0 # 0: updateWithOverwrite 1: updateWithMax
  # point_clout_sensor:
  #   data_type: PointCloud2
  #   topic: camera/depth/points
  #   marking: true
  #   clearing: true
  #   min_obstacle_height: 0.0
  #   max_obstacle_height: 2.5
  #   sensor_frame: camera_color_optical_frame

inflation_layer:
  enabled:              true
  cost_scaling_factor:  15.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.1  # max. distance from an obstacle at which costs are incurred for planning paths.

# inflation_layer2:
#   enabled:              true
#   cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
#   inflation_radius:     0.1  # max. distance from an obstacle at which costs are incurred for planning paths.

obstacle_detection_layer:
  enabled: true